/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labaims;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.Scanner;
import java.util.concurrent.ThreadLocalRandom;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ncoba
 */
public class LabAims extends javax.swing.JFrame {
    
    String name = "annonymous", dodge = "dodge me!";
    
    Timer t1, t2;
    int 
        xAxis_b1, yAxis_b1, 
        xAxis_l9, yAxis_19,
        xAxis_l10, yAxis_l10, 
        xAxis_l13, yAxis_l13, 
        speed_l9, speed_l10, speed_l13,
        random, random_l9, random_l10, random_l13,
        duration, 
        count=30,
        scoreCurrent = 0, 
        scoreHighest = 0;
    
    boolean 
        pause = true, 
        start = false;
    
    Color
        enemyA,
        enemyB,
        enemyC;
    
    DefaultTableModel model = new DefaultTableModel();
    JTable table = new JTable(model);
    JScrollPane pane = new JScrollPane(table);
    
    String[] scanned = null;
    Path currentRelativePath = Paths.get("");
    String s = currentRelativePath.toAbsolutePath().toString()+"/bin/";
    File directory = new File(s);
    File scoreboard = new File(s+"scoreboard.txt"); 
    File cosmetic = new File(s+"cosmetic.txt"); 
    
    Scanner read;
    
    BufferedWriter write;
    
    ArrayList<Integer> stack = new ArrayList<Integer>();
    Object[][] datasetA;
    Object[] column;
    Object A, B;
    
    Pattern p = Pattern.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$");
    Matcher m;
    
    String 
        colorLMB = "#FF0000",
        colorMMB = "#00FFFF",
        colorRMB = "#FFC0CB";
    
    String 
        content = "",
        tmp = "";
    
    
    
    public LabAims() {
        initComponents();
        
        setLayout(null);
        
        directory.mkdirs();
        try {
            cosmetic.createNewFile();
            scoreboard.createNewFile();
            read = new Scanner(scoreboard);
        } catch (IOException ex) {
        }
        
        column = new Object[]{"score", "player", "data"};
        
        refreshGUI();
        
        model.setRowCount(0);
        model.setDataVector(datasetA,column);
        
        setTitle("LabAims");
        setSize(400, 400);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Play = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Cosmetic = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));

        b1.setText("jButton1");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b1MousePressed(evt);
            }
        });

        l1.setText("Current Score:");

        l2.setText("Highest Score:");

        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("Time left (seconds): 30");

        l4.setText("left-click enemies:");
        l4.setMaximumSize(new java.awt.Dimension(150, 16));
        l4.setMinimumSize(new java.awt.Dimension(150, 16));
        l4.setPreferredSize(new java.awt.Dimension(150, 16));

        b2.setFocusable(false);
        b2.setMaximumSize(new java.awt.Dimension(15, 15));
        b2.setMinimumSize(new java.awt.Dimension(15, 15));
        b2.setPreferredSize(new java.awt.Dimension(15, 15));
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b2MousePressed(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFocusable(false);
        b3.setMaximumSize(new java.awt.Dimension(15, 15));
        b3.setMinimumSize(new java.awt.Dimension(15, 15));
        b3.setPreferredSize(new java.awt.Dimension(15, 15));
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b3MousePressed(evt);
            }
        });

        l5.setText("middle-click enemies:");
        l5.setMaximumSize(new java.awt.Dimension(150, 16));
        l5.setMinimumSize(new java.awt.Dimension(150, 16));
        l5.setPreferredSize(new java.awt.Dimension(150, 16));

        l6.setText("right-click enemies:");
        l6.setMaximumSize(new java.awt.Dimension(150, 16));
        l6.setMinimumSize(new java.awt.Dimension(150, 16));
        l6.setPreferredSize(new java.awt.Dimension(150, 16));

        b4.setFocusable(false);
        b4.setMaximumSize(new java.awt.Dimension(15, 15));
        b4.setMinimumSize(new java.awt.Dimension(15, 15));
        b4.setPreferredSize(new java.awt.Dimension(15, 15));
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b4MousePressed(evt);
            }
        });

        l7.setText("Name:");

        l8.setText("\"\"");

        l9.setText("dodge me!");
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l9MouseEntered(evt);
            }
        });

        l10.setText("dodge me!");
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l10MouseEntered(evt);
            }
        });

        l11.setText("dodge enemies:");
        l11.setMaximumSize(new java.awt.Dimension(150, 16));
        l11.setMinimumSize(new java.awt.Dimension(150, 16));
        l11.setPreferredSize(new java.awt.Dimension(150, 16));

        l12.setText("\"\"");
        l12.setMaximumSize(new java.awt.Dimension(150, 16));
        l12.setMinimumSize(new java.awt.Dimension(150, 16));
        l12.setPreferredSize(new java.awt.Dimension(150, 16));

        l13.setText("dodge me!");
        l13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l13MouseEntered(evt);
            }
        });

        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Start New");
        jMenuItem1.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuItem1MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Play.add(jMenuItem1);

        jMenuItem2.setText("Resume Or Pause");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Play.add(jMenuItem2);

        jMenuItem10.setText("Refresh");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Play.add(jMenuItem10);

        jMenuItem3.setText("Scoreboard");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Play.add(jMenuItem3);

        jMenuBar1.add(Play);

        Cosmetic.setText("Cosmetic");
        Cosmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosmeticActionPerformed(evt);
            }
        });

        jMenuItem11.setText("Reset");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Cosmetic.add(jMenuItem11);

        jMenuItem4.setText("Set Left Click Enemy's Color");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Cosmetic.add(jMenuItem4);

        jMenuItem5.setText("Set Middle Click Enemy's Color");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Cosmetic.add(jMenuItem5);

        jMenuItem6.setText("Set Right Click Enemy's Color");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Cosmetic.add(jMenuItem6);

        jMenuItem9.setText("Set Dodge Enemy's Label");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Cosmetic.add(jMenuItem9);

        jMenuItem8.setText("Set Player's Name");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Cosmetic.add(jMenuItem8);

        jMenuBar1.add(Cosmetic);

        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Guide");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Help.add(jMenuItem7);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(l13)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(l10)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l7)
                    .addComponent(l8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l3)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l9))
                .addGap(18, 18, 18)
                .addComponent(l13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(l10)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        l6.getAccessibleContext().setAccessibleName("right-click enemies");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void updateGUI(){
        if(scoreCurrent != 0) l1.setText("Current Score: "+scoreCurrent); 
        if(scoreHighest != 0) l2.setText("Highest Score: "+scoreHighest); 
    }
    
    private void refreshGUI(){
        GameOver();
        l8.setText(null);
        l9.setLocation(-50, -15);
        l10.setLocation(-50, -15);
        l13.setLocation(-50, -15);
        l12.setText(null);
        
        l3.setText("Time left (seconds): 30");
        
        b1.setLocation(195, 135);
        b1.setEnabled(false);
        
        cosmeticState();
        scoreBoard();
        l1.setText("Current Score: "+scoreCurrent); 
        if(scoreHighest != 0) l2.setText("Highest Score: "+scoreHighest); 
    }
    
    private void scoreBoard(){
        model.setRowCount(0);
        scanned = null;
        int x = 0, y = 0;
        try {
            scoreboard.createNewFile();
        } catch (IOException ex) {
        }
        try {
            read = new Scanner(scoreboard);
            for(x = 0; read.hasNextLine(); x++){
                x = x;
                scanned = read.nextLine().split(" ");
                y = scanned.length;
            }
        } catch (Exception e) {
        }
        datasetA = new Object[x][y];
        
        try {
            read = new Scanner(scoreboard);
            for(x = 0; read.hasNextLine(); x++){
                try{
                    scanned = read.nextLine().split(" ");
                    for(y = 0; y < scanned.length; y++){
                        datasetA[x][y] = scanned[y];
                    }
                }catch(Exception e){
                    
                }
            }
        } catch (Exception e) {
        }
        scoreSort();
    }
    
    private void scoreSort() {
        Arrays.sort(datasetA, new Comparator<Object[]>() {
            @Override
            public int compare(Object[] a, Object[] b) {
                A = a[0];
                if(A.equals("")) A=0;
                B = b[0];
                if(B.equals("")) B=0;
                return Integer.compare(Integer.valueOf(B.toString()), Integer.valueOf(A.toString()));
            }
        });
        try{
            scoreHighest = Integer.valueOf(datasetA[0][0].toString());
            updateGUI();
        }catch(Exception e){
            l2.setText("Highest Score: ");
        }
    }
    
    private void instantiate_l9(){
        random_l9 = ThreadLocalRandom.current().nextInt(0, 4); 
        if(random_l9 == 0||random_l9 == 1){
            yAxis_19 = ThreadLocalRandom.current().nextInt(0, 325);
            if(random_l9 == 0){
                xAxis_l9 = -50;
            }else if(random_l9 == 1){
                xAxis_l9 = 395;
            }
        }else if(random_l9 == 2||random_l9 == 3){
            xAxis_l9 = ThreadLocalRandom.current().nextInt(0, 345);
            if(random_l9 == 2){
                yAxis_19 = -15;
            }else if(random_l9 == 3){
                yAxis_19 = 340;
            }
        }
        speed_l9 = ThreadLocalRandom.current().nextInt(5, 16);
    }
    private void instantiate_l10(){
        random_l10 = ThreadLocalRandom.current().nextInt(0, 4); 
        if(random_l10 == 0||random_l10 == 1){
            yAxis_l10 = ThreadLocalRandom.current().nextInt(0, 325);
            if(random_l10 == 0){
                xAxis_l10 = -50;
            }else if(random_l10 == 1){
                xAxis_l10 = 395;
            }
        }else if(random_l10 == 2||random_l10 == 3){
            xAxis_l10 = ThreadLocalRandom.current().nextInt(0, 345);
            if(random_l10 == 2){
                yAxis_l10 = -15;
            }else if(random_l10 == 3){
                yAxis_l10 = 340;
            }
        }
        speed_l10 = ThreadLocalRandom.current().nextInt(5, 16);
    }
    private void instantiate_l13(){
        random_l13 = ThreadLocalRandom.current().nextInt(0, 4); 
        if(random_l13 == 0||random_l13 == 1){
            yAxis_l13 = ThreadLocalRandom.current().nextInt(0, 325);
            if(random_l13 == 0){
                xAxis_l13 = -50;
            }else if(random_l13 == 1){
                xAxis_l13 = 395;
            }
        }else if(random_l13 == 2||random_l13 == 3){
            xAxis_l13 = ThreadLocalRandom.current().nextInt(0, 345);
            if(random_l13 == 2){
                yAxis_l13 = -15;
            }else if(random_l13 == 3){
                yAxis_l13 = 340;
            }
        }
        speed_l13 = ThreadLocalRandom.current().nextInt(5, 16);
    }
    
    private void dodgeMe(){
        if(l9.getLocation().x < -50){
            instantiate_l9();
        }else if(l9.getLocation().x > 395){
            instantiate_l9();
        }
        if(l9.getLocation().y < -15){
            instantiate_l9();
        }else if(l9.getLocation().y > 340){
            instantiate_l9();
        }
        if(random_l9 == 0){
            xAxis_l9 += speed_l9;
        }else if(random_l9 == 1){
            xAxis_l9 -= speed_l9;
        }else if(random_l9 == 2){
            yAxis_19 += speed_l9;
        }else if(random_l9 == 3){
            yAxis_19 -= speed_l9;
        }
        l9.setLocation(xAxis_l9, yAxis_19);
        
        if(l10.getLocation().x < -50){
            instantiate_l10();
        }else if(l10.getLocation().x > 395){
            instantiate_l10();
        }
        if(l10.getLocation().y < -15){
            instantiate_l10();
        }else if(l10.getLocation().y > 340){
            instantiate_l10();
        }
        if(random_l10 == 0){
            xAxis_l10 += speed_l10;
        }else if(random_l10 == 1){
            xAxis_l10 -= speed_l10;
        }else if(random_l10 == 2){
            yAxis_l10 += speed_l10;
        }else if(random_l10 == 3){
            yAxis_l10 -= speed_l10;
        }
        l10.setLocation(xAxis_l10, yAxis_l10);
        
        if(l13.getLocation().x < -50){
            instantiate_l13();
        }else if(l13.getLocation().x > 395){
            instantiate_l13();
        }
        if(l13.getLocation().y < -15){
            instantiate_l13();
        }else if(l13.getLocation().y > 340){
            instantiate_l13();
        }
        if(random_l13 == 0){
            xAxis_l13 += speed_l13;
        }else if(random_l13 == 1){
            xAxis_l13 -= speed_l13;
        }else if(random_l13 == 2){
            yAxis_l13 += speed_l13;
        }else if(random_l13 == 3){
            yAxis_l13 -= speed_l13;
        }
        l13.setLocation(xAxis_l13, yAxis_l13);
    }
    
    private void GameOver() {
        buttonState(false);
        pause = true;
        l3.setText("Times Up!");
        try {
            t1.cancel();
            String pattern = "YYYYMMddHHmm";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            String date = simpleDateFormat.format(new Date());
            write = new BufferedWriter(new FileWriter(scoreboard, true));
            if(scoreCurrent != 0){
                write.append("\n"+scoreCurrent+" "+name+" "+date);
                write.flush();
            }
        } catch (Exception e) {
        }
        scoreBoard();
    }
    
    public void cosmeticState(){
        try{
            read = new Scanner(cosmetic);
            if(read.hasNextLine()==false){
                write = new BufferedWriter(new FileWriter(cosmetic)); 
                write.write("lmb "+colorLMB+"\nmmb "+colorMMB+"\nrmb "+colorRMB+"\ndodge "+dodge+"\nname "+name);
                write.close();
            }else{
                read = new Scanner(cosmetic);
                while (read.hasNextLine()) {
                    String currLine = read.nextLine();
                    scanned = currLine.split(" ",2);
                    if(currLine.contains("lmb ")){
                        colorLMB = scanned[1];
                    }else if(currLine.contains("mmb ")){
                        colorMMB = scanned[1];
                    }else if(currLine.contains("rmb ")){
                        colorRMB = scanned[1];
                    }else if(currLine.contains("dodge ")){
                        dodge = scanned[1];
                    }else if(currLine.contains("name ")){
                        name = scanned[1];
                    }
                }
            }
        }catch(Exception e){
            
        }
        enemyA = Color.decode(colorLMB);
        enemyB = Color.decode(colorMMB);
        enemyC = Color.decode(colorRMB);
        
        l8.setText(name);
        l9.setText(dodge);
        l10.setText(dodge);
        l12.setText(dodge);
        l13.setText(dodge);
        
        b2.setBackground(enemyA);
        b3.setBackground(enemyB);
        b4.setBackground(enemyC);
        
        b2.setFocusable(false);
        b3.setFocusable(false);
        b4.setFocusable(false);
        
    }
    
    public void buttonState(boolean state){
        b1.setSelected(state);
        b1.setEnabled(state);
        b1.setFocusable(state);
    }
    
    private void colorRandom() {
        random = ThreadLocalRandom.current().nextInt(0, 3);  
        if(random == 0){
            b1.setBackground(enemyA);
        }else if(random == 1){
            b1.setBackground(enemyB);
        }else if(random == 2){
            b1.setBackground(enemyC);
        }
    }
    
    
    
    private void b1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MousePressed
        xAxis_b1 = ThreadLocalRandom.current().nextInt(50, 350); 
        yAxis_b1 = ThreadLocalRandom.current().nextInt(50, 285);
        
        if(b1.isEnabled() == true){
            if(evt.getButton()==1){         
                if(b1.getBackground() == enemyA){
                    scoreCurrent += 100;
                    b1.setLocation(xAxis_b1, yAxis_b1);

                }else{
                    scoreCurrent -= 1000;
                    b1.setLocation(xAxis_b1, yAxis_b1);
                }
                l1.setText("Current Score: "+scoreCurrent);
            }else if(evt.getButton()==2){         
                if(b1.getBackground() == enemyB){
                    scoreCurrent += 100;
                    b1.setLocation(xAxis_b1, yAxis_b1);

                }else{
                    scoreCurrent -= 1000;
                    b1.setLocation(xAxis_b1, yAxis_b1);
                }
                l1.setText("Current Score: "+scoreCurrent);
            }else if(evt.getButton()==3){         
                if(b1.getBackground() == enemyC){
                    scoreCurrent += 100;
                    b1.setLocation(xAxis_b1, yAxis_b1);

                }else{
                    scoreCurrent -= 1000;
                    b1.setLocation(xAxis_b1, yAxis_b1);
                }
                l1.setText("Current Score: "+scoreCurrent);
            }
            colorRandom();
        }
    }//GEN-LAST:event_b1MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(pause == true){
            pause = false;
        }
        l1.setText("Current Score: ");
        scoreCurrent = 0;
        scoreBoard();
        colorRandom();
        
        b1.setEnabled(true);
        
        try{
            t1.cancel();
        }
        catch(Exception ex){
            
        }
        b1.setLocation(xAxis_b1 = 195, yAxis_b1 = 135);
        t1 = new Timer();
        count = 30;
        t1.schedule(new TimerTask() {
            @Override
            public void run() {
                l3.setText(String.valueOf("Time left (seconds): "+count/10+""+count%10));
                if(pause == false){
                    count--; 
                }
                if(count == 0){
                    GameOver();
                }
            }
        }, 0, 1_000);
        
        try{
            t2.cancel();
        }
        catch(Exception ex){
            
        }
        instantiate_l9();
        instantiate_l10();
        instantiate_l13();
        t2 = new Timer();
        t2.schedule(new TimerTask() {
            @Override
            public void run() {
                if(pause == false){
                    dodgeMe();
                }
                if(count == 0){
                    t2.cancel();
                }
            }
        }, 0, 100);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuItem1MenuKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1MenuKeyPressed
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if(pause == true){
            pause = false;
            buttonState(true);
            
        }else if(pause == false){
            pause = true;
            buttonState(false);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try{
            tmp = JOptionPane.showInputDialog("What Hex Code Color? (Example: #00FFFF)");
            m = p.matcher(tmp);
            read = new Scanner(cosmetic);
            if(m.matches()){
                enemyB = Color.decode(tmp);
                while (read.hasNextLine()) {
                    content = content.concat(read.nextLine() + "\n");
                }
                try{
                    content = content.replaceAll("mmb "+colorMMB, "mmb "+tmp);
                    write = new BufferedWriter(new FileWriter(cosmetic));
                    write.write(content);
                    write.close();
                    colorMMB = tmp;
                } catch (Exception e) {
                }
            }else{
            }
        }catch(Exception e){
            
        }
        cosmeticState();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayActionPerformed

    private void CosmeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosmeticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CosmeticActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_HelpActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        scoreBoard();
        model.setDataVector(datasetA,column);
        table.setModel(model);
        JOptionPane.showMessageDialog(null, pane);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try{
            tmp = JOptionPane.showInputDialog("What Hex Code Color? (Example: #00FFFF)");
            m = p.matcher(tmp);
            read = new Scanner(cosmetic);
            if(m.matches()){
                enemyA = Color.decode(tmp);
                while (read.hasNextLine()) {
                    content = content.concat(read.nextLine() + "\n");
                }
                try{
                    content = content.replaceAll("lmb "+colorLMB, "lmb "+tmp);
                    write = new BufferedWriter(new FileWriter(cosmetic));
                    write.write(content);
                    write.close();
                    colorLMB = tmp;
                } catch (Exception e) {
                }
            }else{
            }
        }catch(Exception e){
            
        }
        cosmeticState();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try{
            tmp = JOptionPane.showInputDialog("What Hex Code Color? (Example: #00FFFF)");
            m = p.matcher(tmp);
            read = new Scanner(cosmetic);
            if(m.matches()){
                enemyC = Color.decode(tmp);
                while (read.hasNextLine()) {
                    content = content.concat(read.nextLine() + "\n");
                }
                try{
                    content = content.replaceAll("rmb "+colorRMB, "rmb "+tmp);
                    write = new BufferedWriter(new FileWriter(cosmetic));
                    write.write(content);
                    write.close();
                    colorRMB = tmp;
                } catch (Exception e) {
                }
            }else{
            }
        }catch(Exception e){
            
        }
        cosmeticState();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void b2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2MousePressed

    private void b3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3MousePressed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Hatdog BIG :O");
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void b4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4MousePressed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        try{
            tmp = JOptionPane.showInputDialog("Name Please?");
            read = new Scanner(cosmetic);
            if(tmp.length()>0){
                while (read.hasNextLine()) {
                    content = content.concat(read.nextLine() + "\n");
                }
                try{
                    content = content.replaceAll("name "+name, "name "+tmp);
                    write = new BufferedWriter(new FileWriter(cosmetic));
                    write.write(content);
                    write.close();
                    name = tmp;
                } catch (Exception e) {
                }
            }
        }catch(Exception e){
            
        }
        cosmeticState();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void l9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseEntered
        if(pause == false){
            scoreCurrent -= 50;
            updateGUI();
        }
    }//GEN-LAST:event_l9MouseEntered

    private void l10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseEntered
        // TODO add your handling code here:
        if(pause == false){
            scoreCurrent -= 50;
            updateGUI();
        }
    }//GEN-LAST:event_l10MouseEntered

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        try{
            tmp = JOptionPane.showInputDialog("Label Please?");
            read = new Scanner(cosmetic);
            if(tmp.length()>5){
                while (read.hasNextLine()) {
                    content = content.concat(read.nextLine() + "\n");
                }
                try{
                    content = content.replaceAll("dodge "+dodge, "dodge "+tmp);
                    write = new BufferedWriter(new FileWriter(cosmetic));
                    write.write(content);
                    write.close();
                    dodge = tmp;
                } catch (Exception e) {
                }
            }else{
                JOptionPane.showMessageDialog(null,"More than 5 characters, PLEZ");
            }
        }catch(Exception e){
            
        }
        cosmeticState();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void l13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l13MouseEntered
        // TODO add your handling code here:
        if(pause == false){
            scoreCurrent -= 50;
            updateGUI();
        }
    }//GEN-LAST:event_l13MouseEntered

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        refreshGUI();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        colorLMB = "#FF0000";
        colorMMB = "#00FFFF";
        colorRMB = "#FFC0CB";
        name = "annonymous!";
        dodge = "dodge me!";
        try{
            write = new BufferedWriter(new FileWriter(cosmetic)); 
            write.write("lmb "+colorLMB+"\nmmb "+colorMMB+"\nrmb "+colorRMB+"\ndodge "+dodge+"\nname "+name);
            write.close();
        }catch(Exception e){
            
        }
        cosmeticState();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabAims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabAims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabAims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabAims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabAims().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cosmetic;
    private javax.swing.JMenu Help;
    private javax.swing.JMenu Play;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
